# Generated by Django 4.1.9 on 2023-07-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("matched", models.BooleanField(default=False)),
                ("match_id", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
