# Generated by Django 4.1.9 on 2023-07-01 16:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("socialLogin", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="name",
            new_name="username",
        ),
    ]
