# Generated by Django 4.1.9 on 2023-07-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("game_id", models.CharField(max_length=32)),
                ("cho_user_id", models.CharField(max_length=50, null=True)),
                ("cho_position", models.CharField(max_length=20, null=True)),
                ("han_user_id", models.CharField(max_length=50, null=True)),
                ("han_position", models.CharField(max_length=20, null=True)),
                ("cho_king", models.CharField(default="e2", max_length=3)),
                ("cho_rook1", models.CharField(default="a1", max_length=3)),
                ("cho_rook2", models.CharField(default="i1", max_length=3)),
                ("cho_knight1", models.CharField(default="b1", max_length=3)),
                ("cho_knight2", models.CharField(default="h1", max_length=3)),
                ("cho_elephant1", models.CharField(default="c1", max_length=3)),
                ("cho_elephant2", models.CharField(default="g1", max_length=3)),
                ("cho_advisor1", models.CharField(default="d1", max_length=3)),
                ("cho_advisor2", models.CharField(default="f1", max_length=3)),
                ("cho_cannon1", models.CharField(default="b3", max_length=3)),
                ("cho_cannon2", models.CharField(default="h3", max_length=3)),
                ("cho_pawn1", models.CharField(default="a4", max_length=3)),
                ("cho_pawn2", models.CharField(default="c4", max_length=3)),
                ("cho_pawn3", models.CharField(default="e4", max_length=3)),
                ("cho_pawn4", models.CharField(default="g4", max_length=3)),
                ("cho_pawn5", models.CharField(default="i4", max_length=3)),
                ("han_king", models.CharField(default="e9", max_length=3)),
                ("han_rook1", models.CharField(default="a10", max_length=3)),
                ("han_rook2", models.CharField(default="i10", max_length=3)),
                ("han_knight1", models.CharField(default="c10", max_length=3)),
                ("han_knight2", models.CharField(default="g10", max_length=3)),
                ("han_elephant1", models.CharField(default="b10", max_length=3)),
                ("han_elephant2", models.CharField(default="h10", max_length=3)),
                ("han_advisor1", models.CharField(default="d10", max_length=3)),
                ("han_advisor2", models.CharField(default="f10", max_length=3)),
                ("han_cannon1", models.CharField(default="b8", max_length=3)),
                ("han_cannon2", models.CharField(default="h8", max_length=3)),
                ("han_pawn1", models.CharField(default="a7", max_length=3)),
                ("han_pawn2", models.CharField(default="c7", max_length=3)),
                ("han_pawn3", models.CharField(default="e7", max_length=3)),
                ("han_pawn4", models.CharField(default="g7", max_length=3)),
                ("han_pawn5", models.CharField(default="i7", max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.CharField(max_length=100)),
                ("match_id", models.CharField(max_length=100)),
            ],
        ),
    ]
