# Generated by Django 4.1.9 on 2023-07-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matching", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchgroup",
            name="user_id1",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="matchgroup",
            name="user_id2",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
