# Generated by Django 4.1.9 on 2023-07-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matching", "0002_matchgroup_user_id1_matchgroup_user_id2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matchingqueue",
            name="additional_info",
        ),
        migrations.AddField(
            model_name="matchingqueue",
            name="match_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="matchingqueue",
            name="status",
            field=models.CharField(default="waiting", max_length=50),
        ),
    ]
