# Generated by Django 4.1.9 on 2023-07-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="* 제목은 최대 100자 이내", max_length=200, verbose_name="제목")),
                ("author", models.CharField(max_length=100, verbose_name="글쓴이")),
                ("content", models.TextField(verbose_name="내용")),
                ("published_date", models.DateTimeField(auto_now=True, verbose_name="등록일")),
            ],
        ),
    ]
